<%@ Page Language="VB" AutoEventWireup="false" CodeFile="free-publishing-guides.aspx.vb"  MasterPageFile="MasterPage.master" Inherits="free_publishing_guides" %>

<asp:Content runat="server" ContentPlaceHolderID="pageContent">




<div class="container-fluid bg-img bg-wood-panel">
    <div class="container">
        <div class="row">
            <section class="jumbotron light">
                <h1 class="title text-center pb-30">BookBaby in the Press</h1>
            </section>
        </div>
    </div>
</div>


<div class="container" id="press-page">
    <div class="row col-xs-12 text-left" style="padding-top:25px;">
        <p class="date">July 13, 2016</p>
        <h2>BookBaby expands Print On Demand service to pay out highest royalties to self-published authors</h2>
        <h3>With POD on BookShop™, indie authors earn more, get paid faster, and enjoy guaranteed in-stock inventory status.</h3>
        <p><em>Pennsauken, NJ</em> – <a href="/">BookBaby</a> today announced its <a href="/print-on-demand">Print On Demand (POD) service</a> is now available through its <a href="/bookshop">BookShop™ direct-to-reader sales website</a>. Authors will earn an industry-leading 50% of the selling price for printed books sold through BookShop while enjoying all the convenience and low inventory costs that make POD an attractive option for authors.</p>
        <p>“Authors haven’t made much money with previous POD programs, and frankly, that’s just wrong,” says BookBaby President Steven Spatz. “When authors sell their printed books through BookBaby’s BookShop, they’ll make more than anywhere else—guaranteed.”</p>
        <p>For example, a typical Digest-sized black and white soft cover that retails for $9.99. Amazon will pay authors between $1.34 to $3.34 royalties. If that same book is sold through BookShop, authors will earn $5.00. BookBaby’s POD service can also include <a href="/hardcover-book-printing">hardcover books</a>, a book selection not found in other POD programs, including CreateSpace.</p>
        <p>BookBaby’s new service addresses two other issues with Print On Demand programs.</p>
        <ul>
            <li>Faster payment: BookBaby deposits authors’ money into their accounts within one week after book orders are shipped. That compares to the standard 90 to 120 days lag in payments from Amazon and others.</li>
            <li>Guaranteed accessibility: Authors’ books are always in stock and ready to ship to readers—a feature exclusive to BookBaby.</li>
        </ul>
        <p>“During last Christmas, every POD program suffered through long periods where books were listed as out of stock,” says Spatz. “Tens of thousands of authors were frustrated by Amazon and Barnes & Noble supply chain breakdowns. But that can’t happen with BookShop. We don’t have to worry about inventory—we print and ship directly out of our factory to the reader. In fact, we guarantee our books are available 24/7 throughout the busiest holiday season. Nobody else in the industry can offer this.”</p>
        <p>BookBaby authors will be seeing more new features and services on the BookShop platform in the coming months. “With this new addition, our self-publishing authors have a true one-stop shop for readers to find more information about our authors and their books,” says Spatz. “It’s a critical resource for achieving success in self-publishing, and BookBaby is the only company that offers it.”</p>
        <p>BookShop is a free online storefront exclusive to BookBaby authors, giving them an easy way to earn more money selling their printed books and eBooks directly to readers. Minimal set-up is required to get started and authors have full control over their page content.</p>
        <p>More information about Print On Demand on BookShop can be found at <a href="/bookshop">https://www.bookbaby.com/bookshop</a>.</p>
        <p><strong>About BookBaby:</strong> BookBaby makes self-publishing easy: From <a href="/book-printing">book printing</a>, <a href="/ebooks">eBooks</a>, distribution, cover design, and now editing. Since 2011, we’ve helped thousands realize their publishing goals, backed by a 100% satisfaction guarantee.</p>
        <p>BookBaby creates and distributes your printed books and eBooks to the largest distribution network, including Amazon, iBooks, Barnes & Noble, and many other popular retailers worldwide. You’ll keep 100% of your book’s net sales, and retain all rights and creative control.</p>
        <p>Best of all, you can call us at 1-877-961-6878 and talk through the process with a real human being–a fellow writer who’s invested in the success of your book.</p>
        <div class="article-divider"></div>
        <p class="date">June 15, 2016</p>
        <h2>BookBaby Launches Premium Editing Services for Self-Publishing Authors</h2>
        <h3>The nation’s leading self publisher introduces world class editing at working class prices.</h3>
        <p><em>Pennsauken, NJ</em> – <a href="/">BookBaby</a> today introduced its new breakthrough <a href="/book-editing-services">editing service for independent authors</a>. The new editing solution allows self-published authors access to a network of editors of some of today’s bestselling books at affordable prices–up to 50% less than other similar premium options.</p>
        <p><a href="/book-editing-services">BookBaby Editing Services</a> is another big step forward for authors who need a wide range of tools and services to print, promote, and <a href="/book-distribution">sell books</a> on their own.</p>
        <p>“Every book needs editing–that’s an established fact,” says BookBaby President Steven Spatz. “Now every author can get the kind of top-notch editing they need. Our goal was to provide a cost-effective solution for self-publishing authors while maintaining the quality that they expect and deserve.”</p>
        <p>BookBaby’s new program offers two book editing service options, Copy or Line Editing. The typical 60,000-word book will cost under $1,200 for Copy Editing–that’s 30 to 50% lower than other competing premium offers.</p>
        <p>BookBaby’s team of editors is a collective of experienced professionals that hail from all over the world. Each book editor is proficient in line-by-line grammar and consistency edits as well as more complex elements such as tone, transition, and story structure. “Our authors will be working with the very same book editors that the top traditional publishers use,” says Spatz. “They’ve edited NY Times and Amazon best sellers across all genres–from sci-fi to young adult and beyond. Bottom line: Your words are in very good hands.”</p>
        <p>A key factor in self-publishing’s consistent growth is its ability to get books to market faster than traditional releases–and BookBaby Editing Services looks to keep up with the pace. Authors can receive their professionally edited manuscript in as fast as 8 to 10 days, making it one of the most efficient services available.</p>
        <p>“Here’s why our program is different–it’s not just about speed and price. It’s about providing a book editing service that keeps authors’ best interests as the priority,” says Spatz. “Our editing process is personalized by matching authors with book editors that specialize in their respective genres to yield the best possible results. And while the editor’s goal is always to improve the book, we understand this is a subjective process and authors may not always agree with the changes. But authors will always have the final say on their work, retaining control throughout the entire process.”</p>
        <p>More information about BookBaby’s new editing service can be found at <a href="/book-editing-services">https://www.bookbaby.com/book-editing-services/</a>.</p>
        <p><strong>About BookBaby:</strong> BookBaby makes self-publishing easy: From <a href="/book-printing">book printing</a>, <a href="/ebooks">eBooks</a>, distribution, cover design, and now editing. Since 2011, we’ve helped thousands realize their publishing goals, backed by a 100% satisfaction guarantee. BookBaby creates and distributes your printed books and eBooks to the largest distribution network, including Amazon, iBooks, Barnes & Noble, and many other popular retailers worldwide. You’ll keep 100% of your book’s net sales, and retain all rights and creative control. Best of all, you can call us at 1-877-961-6878 and talk through the process with a real human being–a fellow writer who’s invested in the success of your book.</p>
        <div class="article-divider"></div>
        <p class="date">March 2, 2016</p>
        <h2>BookBaby offers a free dialogue writing course for authors</h2>
        <h3>The nation’s leading self-publishing company has teamed up with AutoCrit to help authors strengthen their dialogue writing skills.</h3>
        <p><em>Pennsauken, NJ</em> – <a href="/">BookBaby</a>, along with AutoCrit—an online instant manuscript editor—has announced an exclusive giveaway of a three-part video series dedicated to helping authors write better dialogue for their books.</p>
        <p>This dynamic course explores what makes strong dialogue in a book, why it matters, and how to transform your dialogue into well-written, believable passages that readers will love. The entire course is valued at $199, but BookBaby is giving you the opportunity to <a href="/free-guide/autocrit">get the AutoCrit dialogue series for free</a> for a limited time.</p>
        <p>“When an agent or editor receives an author’s manuscript, he or she will first read the dialogue to determine the book’s quality,” said Jocelyn Pruemer, Owner of AutoCrit. “Dialogue is used as a tool to move the plot forward, describe a setting, or even express a mood. When used effectively, strong dialogue helps your book engage readers on a deeper level and provides an overall greater experience.”</p>
        <p>The complete course touches on dialogue writing essentials including:</p>
        <ul>
            <li>Proper dialogue tag use</li>
            <li>Showing versus telling</li>
            <li>Manipulating tone and energy</li>
            <li>Grammar, punctuation, and formatting</li>
            <li>Avoiding cliché and stilted dialogue</li>
            <li>Sounding plausible and realistic</li>
            <li>And much more!</li>
        </ul>
        <p></p>
        <p>“Our goal is to help every author publish successfully, and partnering with AutoCrit gives BookBaby authors the opportunity to improve their writing abilities and increase their chances of success,” said Steven Spatz, BookBaby President. “There’s plenty of value within each session for first timers and more experienced authors.”</p>
        <p>Authors looking to write dynamic dialogue can begin their sessions at <a href="/free-guide/autocrit">https://www.bookbaby.com/free-guide/autocrit</a> .</p>
        <p><strong>About BookBaby:</strong> BookBaby has created the world’s largest eBook and printed book distribution network for self-published authors around the globe. The company distributes books in over 170 countries through more than 100+ online retail stores, including Amazon, iBooks, Barnes & Noble, Powell’s, Kobo, and wholesale networks including Baker & Taylor and Ingram. BookBaby offers a full array of <a href="/self-publishing-book-services">publishing services</a> including eBook conversion and cover design, as well as book printing, page formatting and <a href="/print-on-demand">Print On Demand services</a>. The company also gives each of their authors access to <a href="/bookpromo">BookPromo™</a>, a suite of promotional book services, and <a href="/bookshop">BookShop™</a>, a webpage with an ecommerce option for authors to sell direct to readers. With offices in Portland, Oregon and the Philadelphia area, BookBaby is the sister company to CD Baby — the world's largest online distributor of independent music.</p>
        <div class="article-divider"></div>
        <p class="date">October 28, 2015</p>
        <h2>BookBaby helps authors scale their Mt. NaNoWriMo writing challenge</h2>
        <h3>Beware of the LiterarYeti! Leading self-publishing company creates unique motivational calendar to help writers climb towards their 50,000-word goal</h3>
        <p><em>Pennsauken, NJ</em> – <a href="/">BookBaby</a>, the nation's leading self-publishing company, is climbing new heights to help motivate writers embarking on the National Novel Writing Month (NaNoWriMo) challenge. The company has created exclusive articles, writing tips, and a whimsical word-count calendar to help writers track their progress to the top of their novel writing summit.</p>
        <p>BookBaby's writing challenge theme for 2015 is "Mt. NaNoWriMo," a 50,000 word summit that's guarded by the mythical beast, the LiterarYeti. This fearsome-looking-but-friendly creature even has his own Twitter (<a href="https://twitter.com/literaryeti">@LiterarYeti</a>) and <a href="https://instagram.com/literaryeti">LiterarYeti Instagram</a> accounts. The motivational calendar helps authors to plan out their writing efforts, breaking the daunting 50,000 word task into smaller, more achievable goals.</p>
        <p>NaNoWriMo participants can download a PDF of the <a href="http://blog.bookbaby.com/nanowrimo/">BookBaby Mt. NaNoWriMo word count calendar</a> on our blog.</p>
        <p>"Writing a 50,000 word novel really is like climbing a mountain," said Steven Spatz, BookBaby President. "It's hard yet rewarding work. But that doesn't mean you can't also have a little fun along the way. NaNoWriMo is making a huge impact in the development of young writers around the globe, and our team has gone all-out to create something special for all the participants this year."</p>
        <p>"BookBaby has been a long-term supporter of NaNoWriMo and helped many writers on the next stage of their creative journey, publishing a book," said Grant Faulkner, Executive Director, National Novel Writing Month. "As a tiny nonprofit that puts on the world's largest writing event, BookBaby's support is crucial to helping NaNoWriMo spread the transformational magic of creativity." Last year over 325,000 writers participated in NaNoWriMo, with over 58,000 writers making their goal. Its programs now also include Camp NaNoWriMo during the spring and summer months, and the Young Writer's Program, along with its headline event each November. Over 250 NaNoWriMo novels have been traditionally published including Sara Gruen's <em>Water for Elephants</em>, Erin Morgenstern's <em>The Night Circus</em>, Hugh Howey's <em>Wool</em>, and Rainbow Rowell's <em>Fangirl</em>.</p>
        <p><strong>About BookBaby:</strong> BookBaby has created the world's largest eBook and printed book distribution network for self-published authors around the globe. The company distributes books in over 170 countries through more than 100+ online retail stores, including Amazon, iBooks, Barnes & Noble, Powell's, Kobo, and wholesale networks including Baker & Taylor and Ingram. BookBaby offers a full array of <a href="/self-publishing-book-services">publishing services</a> including eBook conversion and cover design, as well as book printing, page formatting and <a href="/print-on-demand">Print On Demand services</a>. The company also gives each of their authors access to BookPromo™, a suite of promotional book services, and BookShop™, a webpage with an ecommerce option for authors to sell direct to readers. With offices in Portland, Oregon and the Philadelphia area, BookBaby is the sister company to CD Baby — the world's largest online distributor of independent music.</p>
        <div class="article-divider"></div>
        <p class="date">July 1, 2015</p>
        <h2>BookBaby offers free self-publishing strategy eBook for indie authors</h2>
        <h3>Steven Spatz’s new eBook, <em>The End – Now What?!</em>, full of budgeting, manuscript, and publishing advice for authors, is available for the first time as a free download</h3>
        <p><em>Portland, OR</em> – <a href="/">BookBaby</a>, the leading <a href="/ebook-distribution">distributor of eBooks</a> through Amazon, iBooks and other retailers, announced an exclusive giveaway of company president Steven Spatz’s new self-publishing book, <em>The End – Now What?! Six Steps To Take Your Manuscript To the Marketplace In Six Weeks</em>. BookBaby is offering free downloads of the eBook at <a href="/free-guide/the-end?Source=END-BBWEB&initialsource=END-BBWEB&Dest=https://www.pages04.net/discmakers-cdbaby/Web_Leads_Masterlist/TheEnd">http://www.bookbaby.com/free-guide/the-end</a>.</p>
        <p>“Getting your book published can be a long and daunting process,” said Spatz. “That’s the very simple reason why I wrote <em>The End – Now What?!</em>. I’ve talked to hundreds of authors from all walks of life about their self-publishing experiences, both the good and not-so-good journeys. My book combines dozens of their success stories with some great tips and tricks from New York Times bestselling authors Hugh Howey and Dani Shapiro.</p>
        <p>“The result is a step-by-step strategy guide for writer’s that breaks the process down into six bite-size portions that any author can master.” The book normally sells for $12.99, but Spatz and BookBaby will be offering free eBook downloads through July 31st. Readers can choose between ePub, .mobi, or PDF format.</p>
        <p>A veteran direct marketing professional and writer, Spatz was named BookBaby president in October 2014. He loves to hear from authors, editors, and publishers in the BookBaby community with tales of publishing trials and triumphs. You can tell him your story by writing to <a href="mailto:steven@bookbaby.com">steven@bookbaby.com</a>.</p>
        <p><strong>About BookBaby:</strong> BookBaby has created the world’s largest eBook and printed book distribution network for self-published authors around the globe. The company distributes books in over 170 countries through more than 100+ online retail stores, including Amazon, iBooks, Barnes & Noble, Powell’s, Kobo, and wholesale networks including Baker & Taylor and Ingram. BookBaby offers a full array of <a href="/self-publishing-book-services">publishing services</a> including eBook conversion and cover design, as well as book printing, page formatting and <a href="/print-on-demand">Print On Demand services</a>. The company also gives each of their authors access to BookPromo™, a suite of promotional book services, and BookShop™, a webpage with an ecommerce option for authors to sell direct to readers. With offices in Portland, Oregon and the Philadelphia area, BookBaby is the sister company to CD Baby — the world’s largest online distributor of independent music.</p>
        <div class="article-divider"></div>
        <p class="date">May 13, 2015</p>
        <h2>BookBaby Hosts Deluxe Book Publishing Sweepstakes: Release Your Inner Book</h2>
        <h3>Nation’s leading eBook and printed book distributor teams up with Writer’s Digest and Edit911 to give away a rich self-publishing package.</h3>
        <p><em>Portland, OR</em> – Thousands of authors turn to <a href="/">BookBaby</a> to help them release their inner book. Now the company is helping one lucky writer realize that dream in its latest sweepstakes. BookBaby, Writer's Digest, and Edit911 have teamed up to give authors the chance to win a prize package that includes everything needed to help write, edit, and self-publish their book. Authors can enter today at <a href="/free-guide/bookbaby-sweeps-may2015?Source=BBSWEEPS15&initialsource=BBSWEEPS15S&Dest=https://www.pages04.net/discmakers-cdbaby/BookBaby_Sweeps-May2015">www.bookbaby.com/release-your-inner-book-sweepstakes</a></p>
        <p>“This is everything that an aspiring author needs to realize their self-publishing dreams,” says Steven Spatz, President of BookBaby.com. “These are all the essentials to creating a quality book and getting it out into the marketplace. With the contributions from our partners Writer’s Digest and Edit911, this prize is going to be a tremendous kick start to the writing career of one lucky author.”</p>
        <p>Valued at nearly $3,000 in goods and services, the award includes the best of BookBaby products and services including eBook publishing, <a href="/complete-self-publishing-package">global eBook and Print On Demand distribution</a> through Amazon, B&N, iBooks, Powells, Baker & Taylor, Ingram and many others, book cover design and 100 <a href="/book-printing">custom printed books.</a></p>
        <p>The lucky winner will also receive products and services from BookBaby partners, including a book editing credit through Edit911, plus a host of products from Writer’s Digest including passes to an upcoming Writer’s Conference. The complete prize package includes:</p>
        <ul class="disc">
            <li>100 Printed Books ($649 value)</li>
            <li>eBook Conversion with Worldwide Distribution ($299 value)</li>
            <li>Print On Demand with Worldwide Distribution ($199 value)</li>
            <li>Deluxe Cover Design ($399 value)</li>
            <li>$500 Credit towards Editing Services ($500 value)</li>
            <li>2015 Writer's Digest Conference Pass ($449 value)</li>
            <li>1-Year Subscription to Writer's Digest Online Tutorials ($199 value)</li>
            <li>Writer’s Digest 1-Year Subscription ($55.92 value)</li>
            <li>Suite of Writer’s Digest Books</li>
            <li>You’ve Got a Book in You ($19.99 value)</li>
            <li>The Author Training Manual ($19.99 value)</li>
            <li>The Writer’s Idea Book ($19.99 value)</li>
            <li>90 Days to Your Novel ($16.99 value)</li>
            <li>Revision and Self-Editing for Publication ($17.99 value)</li>
            <li>Scrivener Story Writing Software ($45 value)</li>
        </ul><strong>Total value: $2,889.87</strong>
        <p></p>
        <p>The BookBaby Release Your Inner Book Sweepstakes is open to any resident of the United States. Giveaway ends June 15, 2015. Full terms and conditions are available <a href="/free-guide/bookbaby-sweeps-may2015-legal.aspx">here</a>.</p>
        <p><strong>About BookBaby:</strong> BookBaby has created the world’s largest eBook and printed book distribution network for self-published authors around the globe. The company distributes books in over 170 countries through more than 100+ online retail stores, including Amazon, iBooks, Barnes & Noble, Powells, Kobo, and wholesale networks including Baker & Taylor and Ingram. BookBaby offers a full array of publishing services including eBook conversion and cover design, as well as book printing, page formatting and print on demand services. The company also gives each of their authors access to BookPromo™, a suite of promotional book services, and <a href="/bookshop">BookShop™</a>, a webpage with an ecommerce option for authors to sell direct to readers. With offices in Portland, Oregon and the Philadelphia area, BookBaby is the sister company to CD Baby -- the world’s largest online distributor of independent music.</p>
        <div class="article-divider"></div>
        <p class="date">January 29, 2015</p>
        <h2>BookBaby Introduces Print On Demand Books with the Industry’s Widest Distribution Network</h2>
        <h3>Self-published authors can now gain unprecedented worldwide book distribution for both eBooks and printed books in 100+ stores and catalogs.</h3>
        <p><em>Portland, OR</em> – <a href="/">BookBaby</a>, the self-publishing powerhouse, announces a game-changing <a href="/print-on-demand">on demand book printing</a> and distribution service that gives authors and publishers the chance to <a href="/ebook-distribution">sell their printed books</a> in dozens of stores and catalogs, including Amazon, Barnes & Noble, and Powell’s, as well as the complete Ingram and Baker & Taylor networks. Combined with BookBaby’s popular <a href="/print-on-demand">eBook distribution services</a>, self-published authors can now place their books in over 100+ online stores and catalogs around the globe.</p>
        <p>Print On Demand (POD) allows authors to sell printed books worldwide without paying for large print runs, inventory and warehousing issues, or handling their own order fulfillment. Books are printed and shipped to customers as needed — and because BookBaby’s POD service comes paired with global distribution, sales can come from almost anywhere in the world.</p>
        <p>“This is different from any other Print On Demand program out on the marketplace,” said Steven Spatz, BookBaby President. “Not only do we offer the most robust book distribution network in the business, we also deliver the highest-quality <a href="/book-printing">custom printed books</a> and back that up with a 100% satisfaction guarantee.”</p>
        <p>“Self-published authors need all the exposure they can get for their books. They deserve to have a place on book store shelves around the world, and our program delivers the maximum exposure through retail stores and wholesale catalogs.”</p>
        <p>Unlike other Print On Demand providers, BookBaby uses the very same digital printing presses for their POD books as they do for their larger print runs. “Let’s be honest,” says Spatz. “The print quality for books printed on demand can be spotty. It’s a problem for authors and publishers who get books printed for local sales and also get on-demand printing for global reach because all-too-frequently the book quality differs between the commercially printed books and the POD version. This has been an ongoing problem in the industry for years. BookBaby has changed that. Every single book we print is of the highest-quality in the industry. An author’s first book will be identical to their 1,000th.”</p>
        <p>BookBaby’s Print On Demand service allows authors to concentrate on the essentials of self-publishing success — writing and promotion — and leaves all the manufacturing, book distribution, and shipping work entirely up to BookBaby. Whenever a POD client’s book is purchased in a store, online, or ordered by a wholesaler such as Ingram or Baker & Taylor, BookBaby will print, bind, and ship it within five days.</p>
        <p>“Beautifully printed books, true global reach, low upfront cost, one-time sign up, and sell forever– that’s our on-demand printing service in a nutshell,” says Spatz. “When you add that to our strong eBook program, it means we’re serving 100% of an author’s go-to market needs like no one else in the industry.”</p>
        <p>“For the first time ever, self-published authors can truly be everywhere they need to be, in all formats, in all the important places, with hand crafted quality books they can be proud of.”</p>
        <p>With offices in Portland, Oregon and the Philadelphia area, BookBaby is the sister company to CD Baby, the world’s largest online distributor of independent music. BookBaby offers complete ePublishing and printing services to independent authors.</p>
        <div class="article-divider"></div>
        <p class="date">January 29, 2015</p>
        <h2>BookBaby Introduces Print On Demand Books with the Industry’s Widest Distribution Network</h2>
        <h3>Self-published authors can now gain unprecedented worldwide book distribution for both eBooks and printed books in 100+ stores and catalogs.</h3>
        <p><em>Portland, OR</em> – <a href="/">BookBaby</a>, the self-publishing powerhouse, announces a game-changing <a href="/print-on-demand">on demand book printing</a> and distribution service that gives authors and publishers the chance to <a href="/ebook-distribution">sell their printed books</a> in dozens of stores and catalogs, including Amazon, Barnes & Noble, and Powell’s, as well as the complete Ingram and Baker & Taylor networks. Combined with BookBaby’s popular <a href="/print-on-demand">eBook distribution services</a>, self-published authors can now place their books in over 100+ online stores and catalogs around the globe.</p>
        <p>Print On Demand (POD) allows authors to sell printed books worldwide without paying for large print runs, inventory and warehousing issues, or handling their own order fulfillment. Books are printed and shipped to customers as needed — and because BookBaby’s POD service comes paired with global distribution, sales can come from almost anywhere in the world.</p>
        <p>“This is different from any other Print On Demand program out on the marketplace,” said Steven Spatz, BookBaby President. “Not only do we offer the most robust book distribution network in the business, we also deliver the highest-quality <a href="/book-printing">custom printed books</a> and back that up with a 100% satisfaction guarantee.”</p>
        <p>“Self-published authors need all the exposure they can get for their books. They deserve to have a place on book store shelves around the world, and our program delivers the maximum exposure through retail stores and wholesale catalogs.”</p>
        <p>Unlike other Print On Demand providers, BookBaby uses the very same digital printing presses for their POD books as they do for their larger print runs. “Let’s be honest,” says Spatz. “The print quality for books printed on demand can be spotty. It’s a problem for authors and publishers who get books printed for local sales and also get on-demand printing for global reach because all-too-frequently the book quality differs between the commercially printed books and the POD version. This has been an ongoing problem in the industry for years. BookBaby has changed that. Every single book we print is of the highest-quality in the industry. An author’s first book will be identical to their 1,000th.”</p>
        <p>BookBaby’s Print On Demand service allows authors to concentrate on the essentials of self-publishing success — writing and promotion — and leaves all the manufacturing, book distribution, and shipping work entirely up to BookBaby. Whenever a POD client’s book is purchased in a store, online, or ordered by a wholesaler such as Ingram or Baker & Taylor, BookBaby will print, bind, and ship it within five days.</p>
        <p>“Beautifully printed books, true global reach, low upfront cost, one-time sign up, and sell forever– that’s our on-demand printing service in a nutshell,” says Spatz. “When you add that to our strong eBook program, it means we’re serving 100% of an author’s go-to market needs like no one else in the industry.”</p>
        <p>“For the first time ever, self-published authors can truly be everywhere they need to be, in all formats, in all the important places, with hand crafted quality books they can be proud of.”</p>
        <p>With offices in Portland, Oregon and the Philadelphia area, BookBaby is the sister company to CD Baby, the world’s largest online distributor of independent music. BookBaby offers complete ePublishing and printing services to independent authors.</p>
        <div class="article-divider"></div>
        <p class="date">December 12, 2014</p>
        <h2>BookBaby adds 50+ stores and more to new eBook publishing package</h2>
        <h3>New, simplified ePublishing offer includes greatly expanded eBook distribution network, additional marketing tools, and even more customer support</h3>
        <p><em>Portland, OR</em> – FOR IMMEDIATE RELEASE – eBook distribution powerhouse <a class="highlight" href="/">BookBaby</a> launched a newly enhanced eBook publishing program today, designed to simplify the digital publishing process for authors around the globe. With <a href="/ebook-distribution">"50+ new eBook stores in its retail network</a>, new book marketing tools, additional customer service support and guaranteed high quality file conversions, all BookBaby authors can now experience a worry-free eBook launch.</p>
        <p>To introduce the new and improved program, BookBaby is offering a $100 discount on their <a href="/ebook-services">eBook conversion and distribution package</a> price for a limited time. The discounted fee will be $199 through February 15, 2015.</p>
        <p>"Our improved eBook publishing package includes free phone and email support, which provides true peace of mind publishing for self-published authors," said Steven Spatz, BookBaby President. "Making an eBook can be a stressful and confusing process. There are many eBook publishing companies to choose from, with pricing ranging from free to over $1,000, each of which require the author to do much - if not all - of the work."</p>
        <p>"We think self-published authors need an expert to call when they have questions – someone to hold their hand through the process. So we decided to make things simple and put our customer service teams in the forefront of every single eBook project. It's what sets us apart from every other eBook distributor in the industry."</p>
        <p>BookBaby has expanded beyond its current Portland, OR-based customer service center with an additional support team in the Philadelphia area, now available to handle questions. "There's nothing like talking to a real live person for help and advice, and our authors know that answers are just a call or email away."</p>
        <p>The improvements to BookBaby's eBook publishing and distribution package include:</p>
        <ul type="disc">
            <li><strong>A massive expansion of eBook retailers.</strong> BookBaby now offers the largest eBook retail network by far - over 60+ stores worldwide including Amazon, iBooks, Barnes & Noble, Kobo and dozens more. "We've always distributed to the majors," explained Spatz, "but now we're putting our authors' books into many new European, Asian, South American and niche retailers that are the leaders in the local marketplace."</li>
            <li>
                <strong>Additional book marketing tools and services.</strong> BookBaby's exclusive <a href="/bookpromo">BookPromo™</a> book promotion tools now include a new step-by-step guide for pinpointing search terms for authors' listings on Amazon. And for the first time ever, BookBaby is allowing authors to make free changes to their books' metadata information — including price adjustments. "Authors told us they really needed to have this free access and we've delivered," said Spatz.
            </li>
            <li><strong>Expanded customer service support hours.</strong> With BookBaby publishing experts now in Philadelphia and Portland, authors can call between 9 AM to 8 PM EST on all business days to quickly resolve any book publishing issues.</li>
            <li><strong>Guaranteed high quality eBook file conversions.</strong> With its new singular program, BookBaby handles all of the technical heavy lifting, taking authors' digital source files in Word, PDF and other popular formats and converting them into ePub and .mobi files to be used in all electronic readers around the globe. "Many authors have neither the time nor expertise to create a really good ePub file," said Spatz. "It's a painstaking, detailed process that's often best left to professionals to ensure the eBook is able to be opened and read on all devices."</li>
        </ul>
        <p></p>
        <p>"Of course," continued Spatz, "this eBook publishing package still includes the thing that made it a game-changer in the industry—a payout of 100% of net online sales. BookBaby still takes a zero percent commission of author sales."</p>
        <p><strong>About BookBaby:</strong> Distributing eBooks in over 170 countries through more than a dozen online retail stores, including Amazon, iBooks, Barnes &amp; Noble, Kobo, and more, BookBaby offers a full array of services including eBook conversion, eBook formatting, cover design and distribution, as well as <a class="highlight" href="/book-printing" target="_blank">short run book printing</a>. The company also gives each of their authors access to <a class="highlight" href="/bookpromo">BookPromo™</a>, a suite of promotional book services, and <a class="highlight" href="/bookshop">BookShop™</a>, a webpage with an ecommerce option for authors to sell direct to readers. Headquartered in Portland, Oregon, BookBaby was launched in early 2011 and applies the same services and powerful resources as sister company CD Baby to the digital publishing world, to help independent authors and publishers accomplish their goals.</p>
        <div class="article-divider"></div>
        <p class="date">October 7, 2014</p>
        <h2>BookBaby Gives Away Free Writer’s Guide to Promote National Novel Writing Month</h2>
        <h3>Free eBook about manuscript preparation and book publishing made available exclusively to NaNoWriMo participants</h3>
        <p><em>Portland, OR</em> – <a class="highlight" href="/">BookBaby</a>,one of the nation&rsquo;s leading book self-publishing companies, has partnered with NaNoWriMo to support National Novel Writing Month, an annual event held in November when more than a quarter of a million writers each work towards the goal of completing a 50,000-word novel. BookBaby is making their informational eBook <a href="/nanowrimo"><em>The End. Now What?! Take Your Manuscript to Marketplace in 6 Weeks</em></a> available to all NaNoWriMo participants as a free PDF, mobi, or ePub download.</p>
        <p>This 105-page eBook, authored by Steven Spatz, BookBaby&rsquo;s newly-announced president, is an updated and expanded version of a guide that thousands of NaNoWriMo writers downloaded earlier this year with the kickoff of Camp NaNoWriMo.</p>
        <p>&ldquo;NaNoWriMo gives authors a thrilling, inspiring, crazy challenge,&nbsp;and BookBaby is always proud to support the event,&rdquo; says Spatz. &ldquo;I&rsquo;m particularly excited this year to give away my new eBook to all of these authors who&rsquo;ll be working hard to finish their own books in 30 days or less. Having recently completed my manuscript for <em>The End. Now What?!</em>, I know there&rsquo;s a certain amount of head scratching that happens once you type that last sentence. My eBook will help writers take their completed manuscripts through the editing, design, conversion, and book distribution processes — and get published the right way.&rdquo;</p>
        <p>This free eBook covers:</p>
        <ul type="disc">
            <li>Manuscript tips from a New York Times bestselling author</li>
            <li>How to find an editor on any budget – even $0</li>
            <li>Choosing a book publishing pathway that&rsquo;s best for you and your writing career</li>
            <li>Often overlooked aspects of book merchandizing</li>
            <li>The importance of your book&rsquo;s cover design</li>
            <li>And more!</li>
        </ul>
        <p></p>
        <p>To download a copy today, go to <a href="/nanowrimo">www.bookbaby.com/nanowrimo</a>.</p>
        <p><strong>About BookBaby:</strong> Distributing eBooks in over 170 countries through more than a dozen online retail stores, including Amazon, iBooks, Barnes &amp; Noble, Kobo, and more, BookBaby offers a full array of services including eBook conversion, eBook formatting, cover design and distribution, as well as <a class="highlight" href="/book-printing" target="_blank">short run book printing</a>. The company also gives each of their authors access to <a class="highlight" href="/bookpromo">BookPromo™</a>, a suite of promotional book services, and <a class="highlight" href="/bookshop">BookShop™</a>, a webpage with an ecommerce option for authors to sell direct to readers. Headquartered in Portland, Oregon, BookBaby was launched in early 2011 and applies the same services and powerful resources as sister company CD Baby to the digital publishing world, to help independent authors and publishers accomplish their goals.</p>
        <div class="article-divider"></div>
        <p class="date">September 18, 2014</p>
        <h2>BookBaby Announces New President</h2>
        <h3>The ePublishing giant taps Steven Spatz to lead new developments, offers</h3>
        <p><em>Pennsauken, NJ</em> – <a class="highlight" href="/">BookBaby</a>, the leading distributor of eBooks through Amazon, iBooks and other retailers, has chosen Steven Spatz as their new president. Spatz has been the Chief Marketing Officer for <a class="highlight" href="http://www.avldigital.com" target="_blank">Audio Video Labs</a> (BookBaby’s parent company) for much of the past 10 years. He’s contributed to many of BookBaby’s recent breakthrough new product developments including <a class="highlight" href="/bookpromo">BookPromo™</a>—a free suite of promotional services to help authors promote and market their books—and <a class="highlight" href="/bookshop">BookShop™</a>, an ecommerce web page where authors can promote and sell their eBooks direct to readers.</p>
        <p>“Steven has been an invaluable marketer for AVL on the music side of the business,” said AVL CEO Tony van Veen. “But he took a special interest in BookBaby from day one of this brand and we’re excited to see what he can do with the business.”</p>
        <p>“I’ve watched this company grow from its origins as CD Baby’s little brother, to become a leader in its field,” said Spatz. “I can’t wait to devote 100% of my time to this amazing brand.”</p>
        <p>Prior to serving as AVL’s chief marketer, Spatz worked with several leading direct marketing businesses including Matchbox Collectibles, Mattel Specialty Retail and Hasbro’s GI Joe Collectibles. He got started in direct to consumer retailing through his family’s business, Pinnacle Orchards, a gourmet fruit and food catalog, after moving on from a short lived stint in newspaper reporting.</p>
        <p>“My background is in journalism, so writing is in my DNA. That’s what makes BookBaby such a perfect fit for me.”</p>
        <p>Spatz takes the helm at BookBaby with the understanding that the self-publishing landscape has quickly evolved past distribution as the end goal. “Authors used to be thrilled to have their books listed on Amazon and all the rest,” he said. “Today those same authors aren’t content to just have their books up for sale online. They want to get noticed by readers and become the next rising star, like Hugh Howey.”</p>
        <p>The key to self-published authors finding their audience, according to Spatz, may lie in the two promotion and sales tools that every BookBaby author enjoys. “BookPromo™ has been a slam dunk winner for our authors. After all, every author wants discoverability and BookPromo™ absolutely helps with that,” said Spatz. “By selling their books through their own BookShop™, our authors get paid more than any other retail offers, plus they get paid much faster. What author wouldn’t like that?”</p>
        <p>Spatz has been the author of many of the <a class="highlight" href="/free-publishing-guides">self-publishing guides for authors</a> offered on the BookBaby website. His upcoming book, <em>The End – What’s Next: Six steps to take your manuscript to the marketplace in six weeks</em> is based upon one of the brand’s most popular guides. The book is scheduled to be released in late fall.</p>
        <p><strong>About BookBaby</strong> Distributing eBooks in over 170 countries through 12 online retail stores, including Amazon, Apple, Barnes & Noble and more, BookBaby offers a full array of services including eBook formatting, cover design and distribution, as well as <a class="highlight" href="/book-printing" target="_blank">short run book printing</a>. The company also gives each of their authors access to BookPromo™, a suite of promotional book services, and BookShop™, a webpage with an ecommerce option for authors to sell direct to readers. Headquartered in Portland, Oregon, BookBaby was launched in early 2011 and applies the same services and powerful resources as sister company CD Baby to the digital publishing world, to help independent authors and publishers accomplish their goals.</p>
        <div class="article-divider"></div>
        <p class="date">June 16, 2014</p>
        <h2>BookBaby Offering Free Guy Kawasaki Book on How to Publish an eBook</h2>
        <h3>eBook distributor partners with self-publishing pioneer in free giveaway of “APE”</h3>
        <p><em>PORTLAND, OR</em> – <a class="highlight" href="/">BookBaby</a>, the leading distributor of eBooks through Amazon, iBooks and other retailers, announced an exclusive free giveaway of Guy Kawasaki’s landmark self-publishing book — <a class="highlight" href="/free-guide/ape-guide?Source=APEPRESS&Dest=https://www.pages04.net/discmakers-cdbaby/BookBaby_GuyKawasaki/APE_guide"><em>APE: How to Publish a Book</em></a>. <em>APE</em>, which stands for Author, Publisher, Entrepreneur, is the twelfth book from the New York Times bestselling business author. BookBaby is offering free downloads of the eBook through the end of July.</p>
        <p><em>APE</em>, co-written by Shawn Welch, is the most complete guide yet available for authors looking to self-publish their book. It offers detailed information for converting, publishing, and selling eBooks.</p>
        <p>“If you are planning on <a class="highlight" href="/ebook-services">publishing an eBook</a>, this is an absolute must-read,” said Steven Spatz, Chief Marketing Officer of BookBaby. “And BookBaby is proud to be able to give away copies of this amazing book for free.”</p>
        <p>This eBook normally sells for $10, but the authors are letting BookBaby offer downloads for free through July 31st. Readers can choose between ePub, .mobi, or PDF format.</p>
        <p>“We wrote <em>APE</em> to empower readers to self-publish,” said Guy Kawaski, co-author of <em>APE:How to Publish a Book.</em> “Partnering with BookBaby in this promo was a no-brainer. They simplify a lot of hurdles artisanal publishers face.”</p>
        <p>Guy Kawasaki is the author of eleven previous books, including <em>What the Plus!</em>, <em>Enchantment</em> , and <em>The Art of the Start</em>. He is also the cofounder of Alltop.com and the former chief evangelist of Apple.</p>
        <p>Shawn Welch is the author of two previous books, including From <em>Idea to App</em>, and <em>iOS 5 Core Frameworks</em>. He is also the developer of several iOS applications.</p>
        <p>Readers can get a free copy of the book on how to self-publish by visiting <a class="highlight" href="/free-guide/ape-guide?Source=APEPRESS&Dest=https://www.pages04.net/discmakers-cdbaby/BookBaby_GuyKawasaki/APE_guide">www.bookbaby.com/apebook</a>.</p>
        <p><strong>About BookBaby</strong><br>
        Distributing eBooks in 170 countries through 12 online retail stores, including Amazon, Apple, Barnes & Noble and more, BookBaby offers a full array of services including eBook formatting, cover design and distribution, as well as <a class="highlight" href="/book-printing">short run book printing</a>. The company also gives each of their authors access to BookPromo™, a suite of promotional book services, and full array of services including eBook formatting, cover design and distribution, as well as <a class="highlight" href="/bookshop">BookShop</a>, a webpage with an ecommerce option for authors to sell direct to readers. Headquartered in Portland, Oregon, BookBaby was launched in early 2011 and applies the same services and powerful resources as sister company CD Baby to the digital publishing world, to help independent authors and publishers accomplish their goals.</p>
        <div class="article-divider"></div>
        <p class="date">May 29, 2014</p>
        <h2>BookBaby announces volume pricing discounts for publishers and agents</h2>
        <h3>eBook distribution powerhouse makes it easy and affordable for publishers to manage global eBook sales for all their authors</h3>
        <p><em>PORTLAND, OR</em> – <a class="highlight" href="/">BookBaby</a>, the leading distributor of eBooks through Amazon, iBooks and many others, launches a new wholesale program today, focusing on the needs of publishers, agents, and others with sizable book catalogs and backlists. Featuring deep volume discounts and exclusive eBook file conversion offers, BookBaby is extending its industry-leading eBook distribution and <a class="highlight" href="/bookpromo">promotional book services</a> beyond self-published authors directly to the book trade.</p>
        <p>More details about the program can be found at <a class="highlight" href="/wholesale">www.bookbaby.com/wholesale</a>. BookBaby’s new wholesale team can be contacted at 856-661-3881.</p>
        <p>“Publishers and agents want the same exact things that self-published authors want – easy eBook file conversions, worldwide distribution and book promotional tools,” said Steven Spatz, Chief Marketing Officer of BookBaby and parent company AVL Digital. “These new BookBaby offers and programs make it even more affordable for publishers, agents, and anyone with a large number of books to get them into the digital marketplace.”</p>
        <p>“Book industry people know that BookBaby offers proven tools to manage their books, distribution, and sales reporting,” said Spatz. ”With our long track record of digital distribution and payment management through sister company CD Baby, publishers can trust us to do the job right.”</p>
        <p>The new <a class="highlight" href="/wholesale">BookBaby wholesale program</a> offers publisher and agents many eBook distribution benefits including:</p>
        <ul>
            <li>Volume discounts up to 30% off eBook publishing packages – Publishers and agents who are distributing 50+ eBooks per year can apply for BookBaby wholesale pricing and set up an individualized plan.</li>
            <li>Payment of up to 100% of net sales – Publishers and agents can choose BookBaby’s Premium eBook publishing package that features 0% commission on all sales through the company’s retail partners.</li>
            <li>Distribution to all leading e-tailers administered through a single BookBaby account – BookBaby distributes worldwide to Amazon, iBooks, Barnes & Noble, Baker & Taylor and many others. It’s the largest eBook distribution network available for self-published authors.</li>
            <li>Centralized metadata management – Publishers, agents or authors control the book’s price, marketing description and other metadata, inputting critical information through one single BookBaby account, and the information is transmitted to all 12 BookBaby retailers.</li>
            <li>Aggregated sales reporting updated weekly – As payments are received from all of BookBaby’s retail partners, BookBaby reports sales into the user account dashboard. Users can perform custom queries to provide authors granular sales reporting by title, date and retailer.</li>
        </ul>
        <p></p>
        <p>BookBaby has deep experience in digital distribution and strong vendor relationships with Amazon, Apple, and other leading companies. As a member of the CD Baby family of brands (the world's largest online distributor of independent music with over $300 million paid directly to artists), BookBaby is well positioned to help publishers, agents, and authors reap the maximum profits in the eBook marketplace.</p>
        <p>The announcement of the company’s new wholesale focus coincides with the start of Book Expo America in New York City, the largest annual event for the book industry. BookBaby is exhibiting at #BEA14 (Booth DZ2056) and is a sponsor of uPubU Conference for self published authors, running concurrently with BEA.</p>
        <div class="article-divider"></div>
        <p class="date">May 5, 2014</p>
        <h2>BookBaby lets authors sell eBooks direct and earn more</h2>
        <h3>Authors can publish, promote and sell their eBooks like never before with the addition of BookShop.</h3>
        <p><em>PORTLAND, OR</em> – <a class="highlight" href="/">BookBaby</a>, the publishing arm of indie music powerhouse CD Baby, is writing a whole new chapter in self publishing with the opening of <a class="highlight" href="/bookshop">BookShop</a>. All BookBaby authors can now sell their eBooks directly to readers through their own free BookShop e-commerce webpage, earning more money per sale and getting paid faster than ever before.</p>
        <p>BookBaby authors will now be able to sell ePub and .mobi versions of their eBooks directly to their readers (earning 85% of the gross selling price) and also link fans to their eBook on popular retail sites such as iBooks, Amazon, Barnes & Noble, and others. What’s more, instead of holding onto authors’ money for weeks or even months like other distributors and retailers, BookBaby pays its authors within one week of the sale.</p>
        <p>“It’s very simple. BookShop pays more and pays fast. Faster than anyone else,” said Steven Spatz, Chief Marketing Officer for BookBaby. “That’s what every author is looking for. For example if you sell an eBook for ten bucks on a Friday, you’ll see $8.50 show up in your account the following Monday. No other company gets money back to its authors like BookBaby.”</p>
        <p>BookShop is free to every BookBaby author, including writers who are now taking advantage of the company’s new FREE eBook publishing package. Authors can upload ePub files directly to BookBaby for worldwide eBook distribution without any upfront costs.</p>
        <p>BookShop is the latest addition to BookBaby’s fast-growing list of products and services to help authors find success in the marketplace. “It used to be that writers were thrilled just to have their manuscripts turned into an eBook and listed for sale on Amazon," said Spatz. “But for today's independent author, literary success requires a lot more than just great file conversion and retail distribution."</p>
        <p>“BookBaby’s new motto is ‘publish, promote and sell.’ While we’ll always help our authors publish books, they also need the opportunity to promote and sell their books. We’ve given our BookBaby authors exactly that with BookPromo™ and now BookShop.”</p>
        <p><a class="highlight" href="/bookshop/"><strong>BookPromo™</strong></a>, a free promotional service for all BookBaby authors, debuted in late 2013 and continues to grow with new products and placements with many of the industry’s top promotional companies including GoodReads, PR Newswire, Reader’s Favorite and many more. BookPromo™ features book discovery placements, free reviews, promotional opportunities and resources.</p>
        <p>BookBaby is the sister company to CD Baby, the world’s largest online distributor of independent music. Founded as a garage start-up in 1998, CD Baby has grown to become one of the most trusted names in the independent music business, paying over a quarter billion dollars to over 300,000 artists worldwide. The company’s newest brand is following in the footsteps of its corporate sibling by helping independent authors realize their literary dreams. “With CD Baby we’ve brought musicians and fans directly together,” said Spatz. “BookBaby and BookShop are going to do exactly the same for authors and readers. First BookPromo™ and now BookShop - it’s clear that BookBaby is turning the page. It’s a whole new chapter in self publishing.”</p>
        <p><strong>About BookBaby</strong></p>
        <p>Distributing eBooks in 170 countries through 12 online retail stores, including Amazon, Apple, Barnes & Noble and more, BookBaby offers a full array of services including eBook formatting, cover design and distribution, as well as <a class="highlight" href="/book-printing">short run book printing</a>. Headquartered in Portland, Oregon, BookBaby was launched in early 2011 and applies the same services and powerful resources as sister company CD Baby to the digital publishing world, to help independent authors and publishers accomplish their goals.</p>
        <div class="article-divider"></div>
        <p class="date">October 8, 2013</p>
        <h2>BookBaby Offers Free Social Media Guide to NaNoWriMo Authors</h2>
        <h3>Indie publishing leader supports National Novel Writing Month organization with its exclusive <em>Twitter for Authors in Ten Minutes a Day</em> giveaway.</h3>
        <p><em>PORTLAND, OR</em> – <a class="highlight" href="/">BookBaby</a>, the largest eBook distributor for independent authors, along with NaNoWriMo.org, announces the release of its latest social media promotion guide entitled <a class="highlight" href="/campaigns/request-nanowrimo-twitter?Source=NANOWRIMO&Dest=https://www.pages04.net/discmakers-cdbaby/BookBaby_NaNoWriMo/NaNoWriMo_Twitter">Twitter for Authors in Ten Minutes a Day</a>. Participants in the upcoming National Novel Writing Month project will be offered this exclusive guide outlining strategies for authors to effectively promote books on Twitter, the popular social media network.</p>
        <p>The latest in a collection of must-have guides for prospective authors, Twitter for Authors in Ten Minutes a Day covers such topics as:</p>
        <ul>
            <li>Why Twitter is better than Facebook</li>
            <li>How to gain followers on Twitter</li>
            <li>How to compose the most effective tweets</li>
            <li>How to schedule tweets and when to tweet</li>
            <li>Auto tweet etiquette</li>
            <li>And much more.</li>
        </ul>
        <p>NaNoWrMo participants can download the free guide at <a class="highlight" href="/campaigns/request-nanowrimo-twitter?Source=NANOWRIMO&Dest=https://www.pages04.net/discmakers-cdbaby/BookBaby_NaNoWriMo/NaNoWriMo_Twitter">http://www.bookbaby.com/nanowrimo</a>.</p>
        <p>“We believe that everyone has a story to tell, and you learn how to write a novel by sitting down and writing it,” said executive NaNoWriMo director Grant Faulkner. “The same do-it-yourself attitude is at the heart of indie book publishing, which is why we’re happy that BookBaby is providing resources for NaNo authors to take that next big step: publishing and finding an audience of readers.”</p>
        <p>According to Faulkner, NaNoWriMo is for anyone who has ever thought fleetingly about writing a novel. NaNoWriMo challenges participants to write 50,000 words of a new novel between November 1 and 30, and over 340,000 writers took up the challenge in 2012.</p>
        <p>Distributing eBooks in 170 countries through 12 online retail stores, including Amazon, Apple, Barnes & Noble and more, BookBaby offers a full array of services including eBook formatting, cover design, and distribution, as well as <a class="highlight" href="/book-printing">short run book printing</a>. BookBaby is the sister company of online music powerhouse CD Baby. Headquartered in Portland, Oregon, CD Baby is the world's largest online distributor of independent music. Since 1999 the company has helped almost a million indie musicians sell their music, paying over $290 million back to artists in the process. In launching BookBaby in early 2011, the company is taking those same services and powerful resources to the digital publishing world to help independent authors and publishers accomplish their goals.</p>
        <p>For more information please contact:<br>
        Steven Spatz, Chief Marketing Officer<br>
        856-661-3373, <a class="highlight" href="mailto:sspatz@bookbaby.com">sspatz@bookbaby.com</a></p>
        <div class="article-divider"></div>
        <p class="date">March 6, 2013</p>
        <h2>eBook Distribution Powerhouse BookBaby Partners with Scribd, the “Social Network for Reading”</h2>
        <h3>Scribd, the world’s largest online library, will now include books by thousands of independent authors represented by BookBaby, making it easy for readers to access those titles from any web-enabled device.</h3>
        <p><em>PORTLAND, OR</em> – BookBaby, already the largest <a class="highlight" href="/ebook-distribution">eBook distribution network</a> for independent authors, has announced the further expansion of its network through a new partnership with Scribd, the world’s largest online library of stories, novels, essays, and more. Scribd, which has been called “the social network for reading,” allows users to access a vast cloud-based library from any computer or mobile device.</p>
        <p>“Scribd is one of the best book-discovery tools out there, and I’m thrilled that BookBaby authors will now be able to leverage those features to sell more eBooks,” says BookBaby president Brian Felsen. “Independent authors will now be included in Scribd’s catalog, alongside the catalogs of over 150 publishers.”</p>
        <p>Scribd’s iPaper technology (a rich document format similar to PDF) displays each title in its own web-based iPaper viewer, allowing users to embed the document on other websites and blogs while preserving its original format. Readers can sample up to 10% of an eBook for free, after which point they must pay to access the complete document — readable “in the cloud” from any computer or mobile device.</p>
        <p>“Scribd has converted over a billion pages of written works into web-pages,” says Felsen. “Over a million people visit Scribd every day to discuss business presentations, poetry, the latest bestsellers, and magazine articles. It’s a huge community of avid and engaged readers — and now they’ll be able to read and discuss the work of BookBaby’s independent authors too.”</p>
        <p>In addition to Scribd, BookBaby’s <a class="highlight" href="/free-guide/bookbaby-catalog?Source=CATALOG-BBWEB&Dest=https://www.pages04.net/discmakers-cdbaby/Web_Leads_Masterlist/BookBaby_Catalog">eBook distribution network</a> includes iBooks (for iPad), Amazon (for Kindle), Barnes & Noble (for Nook), Kobo, Copia, Gardners, Baker & Taylor, eBookPie, and eSentral (the biggest eBook retailer in Asia). With BookBaby, independent authors keep up to 100% of the net revenue generated from their eBook sales. Visit BookBaby.com for more information about <a class="highlight" href="/ebook-publishing/publish-on-scribd">publishing your book for Scribd.</a></p>
        <p>BookBaby is a leading <a class="highlight" href="/">eBook publishing company</a> for independent authors. The company offers a full array of services including eBook formatting, cover design, and distribution, as well as short run book printing. BookBaby is part of the AVL Digital family of businesses, which also includes Disc Makers, CD Baby, and HostBaby.</p>
        <p>For more information please contact:<br>
        Steven Spatz, Chief Marketing Officer<br>
        856-661-3373, <a class="highlight" href="mailto:sspatz@bookbaby.com">sspatz@bookbaby.com</a></p>
        <div class="article-divider"></div>
        <p class="date">February 18, 2013</p>
        <h2>BookBaby Releases Free eBook Marketing Guide: Making Money With Your eBook</h2>
        <h3>Written by a marketer for would-be book marketers, BookBaby’s latest guide helps authors unlock the secrets to simple yet powerful marketing strategies</h3>
        <p><em>PORTLAND, OR</em> – BookBaby announces the release of its latest guide for authors entitled <a class="highlight" href="/free-guide/marketing-your-ebook?Source=MONEY-BBWEB&Dest=https://www.pages04.net/discmakers-cdbaby/Web_Leads_Masterlist/Making_Money_With_Your_eBook_Guide">Making Money With Your eBook</a>, urging authors to “think like a marketer and sell your book like a pro.”</p>
        <p>BookBaby has helped thousands of authors realize the dream of publishing their books, and now the company is helping them take that next step -- successful marketing and sales of their eBooks. Written by Steven Spatz, Chief Marketing Officer for BookBaby, the free guide illustrates how authors can utilize many of the same strategies and techniques that marketing professionals use to sell millions of products every day.</p>
        <p>&bull; Learn how to identify potential readers BEFORE you type your first word.<br>
        &bull; Establish your eBook’s selling position, borrowing upon tried-and-true marketing tools.<br>
        &bull; Be here, there and everywhere, and let others sell your book in 1000s of places on the web.</p>
        <p></p>
        <p>The free guide on how to make money with your eBook is available for immediate download at <a class="highlight" href="/free-guide/marketing-your-ebook?Source=MONEY-BBWEB&Dest=https://www.pages04.net/discmakers-cdbaby/Web_Leads_Masterlist/Making_Money_With_Your_eBook_Guide">http://www.bookbaby.com/makingmoney.</a></p>
        <p>“I know that authors can become great marketers because they’re experts at the most important element of marketing -- communication,“ says Spatz. “But they need to stop behaving like an author trying to market a book. When you think like a marketer, you’re giving your eBook the best chance for success. It’s all about putting yourself and your book in the best position to be discovered and read.”</p>
        <p>Distributing eBooks in 170 countries through 12 online retail stores, including Amazon, Apple, Barnes & Noble and more, BookBaby is the sister company of online music powerhouse CD Baby. Headquartered in Portland, Oregon, CD Baby is the world's largest online distributor of independent music. Since 1999 the company has helped almost a million indie musicians sell their music, paying over $260 million back to artists in the process. In launching BookBaby in early 2011, the company is taking those same services and powerful resources to the digital publishing world to help <a class="highlight" href="/">independent authors and publishers</a> accomplish their goals.</p>
        <p>For more information please contact:<br>
        Steven Spatz, Chief Marketing Officer<br>
        856-661-3373, <a class="highlight" href="mailto:sspatz@bookbaby.com">sspatz@bookbaby.com</a></p>
        <div class="article-divider"></div>
        <p class="date">January 21, 2013</p>
        <h2>BookBaby Now Distributes Independent Authors’ eBooks in 170 Countries</h2>
        <p><em>PORTLAND, OR</em> – The world’s largest <a class="highlight" href="/ebook-distribution">eBook distribution</a> network for independent authors just got bigger. BookBaby, the popular one-stop self-publishing solution, just announced a new <a class="highlight" href="/ebook-publishing/publish-on-esentral">partnership with eSentral</a>, the biggest eBook store in Southeast Asia.</p>
        <p>“I’m thrilled to add eSentral to our growing list of partners,” says BookBaby president Brian Felsen. “Now our independent authors can sell their books on the big eBook retail sites in 170 countries — and manage it all from one simple account.”</p>
        <p>BookBaby’s eBook distribution network includes the most popular eBook retailers in the world, including iBooks (for iPad), Amazon (for Kindle), Barnes & Noble (for Nook), Kobo, Copia, Baker & Taylor, Gardners, eBookPie, and now — eSentral. This new partnership enables BookBaby’s independent authors to <a class="highlight" href="/">sell their eBooks</a> in Malaysia, Singapore, and Indonesia — and eSentral will soon be expanding into other countries in Southeast Asia, as well.</p>
        <p>“We want our authors’ work to be available everywhere that matters,” says Felsen. “And we’re thrilled to be working with eSentral to make great independent writing available to millions of book lovers across Southeast Asia.”</p>
        <p>BookBaby is a leading <a class="highlight" href="/free-guide/bookbaby-catalog?Source=CATALOG-BBWEB&Dest=https://www.pages04.net/discmakers-cdbaby/Web_Leads_Masterlist/BookBaby_Catalog">eBook publishing company</a> for independent authors. The company offers a full array of services including eBook formatting, cover design, and distribution, as well as short run book printing. BookBaby is part of the AVL Digital family of businesses, which also includes Disc Makers, CD Baby, and HostBaby.</p>
        <div class="article-divider"></div>
        <p class="date">May 25, 2011</p>
        <h2>BookBaby Introduces HostBaby for Authors, the Easiest Way to Build a Professional Author Website</h2>
        <p><em>NEW YORK, NY</em> – BookExpo America – Independent eBook distributor BookBaby has teamed up with partner company HostBaby to announce the launch of <strong>HostBaby for Authors</strong>.</p>
        <p>This easy-to-use website templating system offers writers complete design control, including drag-and-drop widgets, customizable backgrounds and banner images, social media integration, easy blog capabilities, and unlimited pages, email accounts, mailing list members, and bandwidth.</p>
        <p><strong>No coding required!</strong> HostBaby's intuitive templating system allows even tech-deficient authors to easily build a professional and dynamic website – an essential hub for marketing campaigns, as well as a place to interact with a growing readership. Writers simply choose one of HostBaby's customizable themes, enter information, and instantly publish a polished web 2.0 website at a fraction of the cost of hiring a professional designer.</p>
        <p>"We're thrilled to give authors access to HostBaby's Site Builder tools," says BookBaby president Brian Felsen. "Now you don't have to be a computer geek to make a great author website. Though it still helps if you're a literary geek."</p>
        <p>Features include:</p>
        <ul>
            <li>Easy-to-use drag-and-drop widgets (event calendar, code snippet, text, email-list signup, etc.)</li>
            <li>Syncing of multiple blogs, Facebook, and Twitter</li>
            <li>Unlimited pages and sub-pages, so your site can grow with your career</li>
            <li>Simple uploader for photos, video, and audio, so you can post your readings and workshops for the world</li>
            <li>Email newsletter tool with unlimited mailing list members and unlimited email accounts</li>
            <li>Streaming audio player, photo gallery, video features, events calendar</li>
            <li>Store page to sell your books and chapbooks</li>
            <li>Developer access (including HTML, CSS, and FTP access)</li>
            <li>One free BookBaby submission per year (a $99 value), to distribute your eBook for Kindle, iPad, Nook, and more</li>
        </ul>
        <p>For writers who aren't tech-savvy, HostBaby offers a free one-hour design consultation to help you make tweaks and adjustments. Also, HostBaby services are <strong>free for the first month</strong>, so there is no risk in simply trying it out.</p>
        <p>For more info, visit <a class="highlight" href="/websites-for-authors">www.bookbaby.com/websites-for-authors</a>.</p>
        <div class="article-divider"></div>
        <p class="date">April 4, 2011</p>
        <h2>BookBaby Introduces Cover Design for eBooks</h2>
        <p><em>PORTLAND, OR</em> – Independent eBook distributor now offers affordable cover concepts created by award-winning graphic designers in as fast as two days.</p>
        <p>Independent eBook distributor BookBaby has launched BookBaby Cover Design, the most affordable design service for independent authors. BookBaby, which provides writers with a safe, reliable, and easy way to sell their work to be read on devices like the iPad, iPhone, Kindle, Android, Nook, and Sony Reader, now also gives independent authors the tools they need to stand out in the growing eBook marketplace.</p>
        <p>"The cover of an eBook is one of the most important sales tools for an author," explains BookBaby president Brian Felsen. "Now independent authors have access to award-winning graphic designers who have years of experience creating compelling art for authors, musicians, and filmmakers."</p>
        <p>BookBaby offers two levels of Cover Design Services:</p>
        <ul>
            <li>Basic Design is priced at $149, and BookBaby's design professionals will create an eye-catching and unique eBook cover in as little as three days. The author owns all rights to the artwork and can use this eBook cover wherever they choose to sell their work.</li>
            <li>Deluxe Design is priced at $279 and includes more complex cover design with multiple photos, textures, graphics, fonts, or stylized text. This option gives the author multiple rounds of proofing and revisions without breaking the bank. Authors will see their first proof in just two days.</li>
        </ul>
        <p>In addition to eBook distribution and cover design, BookBaby also provides self-published authors with ISBNs, file formatting, and <a class="highlight" href="/ebook-conversion">free basic ePUB conversion</a>.</p>
        <p><a class="highlight" href="/services/coverdesign">Click here for more information on BookBaby Cover Design</a>.</p>
        <div class="article-divider"></div>
        <p class="date">January 10, 2011</p>
        <h2>BookBaby makes distribution to Kindle, iPad easy for independent writers</h2>
        <p><em>PORTLAND, OR</em> – BookBaby throws open the doors to the electronic publishing and distribution world for independent authors, offering the highest pay-out rate for eBook distribution in the industry. Premium publishing authors will receive 100% of their net sales revenue – paid weekly – generated through all BookBaby's retailer network, including all the majors retailers including Amazon, Apple, Barnes & Noble, and soon, Google.</p>
        <p>To celebrate its debut in the eBook world, BookBaby is offering <a class="highlight" href="/ebook-distribution">worldwide eBook distribution</a> for an introductory price of $99, a $50 discount off the regular price of $149.</p>
        <p>Focusing on products and services for the independent author community, BookBaby is a new division of parent company CD Baby. Over the past decade, CD Baby has paid out over $120 million to indie musicians worldwide, and has helped level the playing field between DIY musicians and major labels by opening worldwide distribution channels to unsigned artists. Now, with their recently launched BookBaby division, they're doing it again for the publishing industry.</p>
        <p>"In just six months since our soft launch, BookBaby has established itself as THE destination for authors looking for a simple, comprehensive solution to their digital distribution needs," says BookBaby president Brian Felsen. "We make it easy: our sign-up includes a free ePUB conversion to ensure your eBook is distributed to all of the largest retailers."</p>
        <p>BookBaby's services are priced to be affordable to independent authors – both established and new – as well as small and medium-sized imprints that need an easy solution for eBook distribution to all major retail outlets. Since the company does not collect a royalty or commission on sales revenue from its authors, it's as if those authors went directly to the retailer to sell their eBooks, with the added convenience of consolidated sales reporting across all retailers, one simple title submission process for all retailers, and weekly payments to authors.</p>
        <p>BookBaby will digitally distribute your work to the <a class="highlight" href="/ebook-distribution">biggest eBook retailers</a> in the world, making your eBook available to be read on all of current – and future – devices:</p>
        <ul>
            <li>Apple iPad (through the iBooks)</li>
            <li>Amazon Kindle</li>
            <li>Barnes & Noble Nook</li>
            <li>Sony Reader</li>
        </ul>
        <p>As part of its simplified eBook program for independent authors, BookBaby offers format conversion services, helping clients to convert .doc, .html or .txt files into ePub, which is rapidly on its way to becoming the new standard format for electronic publishing. BookBaby also specializes in conversion of more complex documents, including tables, graphs, multiple mages, and embedded multimedia files including video and audio clips. (Availability of this service varies between file format and reader device. Special handling and additional charges will apply.)</p>
        <div class="article-divider"></div>
        <div style="clear:left;"></div>
    </div><!-- #content-wrapper -->
</div><!-- #press-page -->



<!--
<div class="container-fluid">
    <div class="container">
        <div class="row">
            <br />
        </div>
    </div>
</div>
-->


</asp:Content>